# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XoxQ9udfXZu49bUBpB_FCwVOE7IvCve1
"""

global lista_datos
lista_datos =[]
global lista_datos2
lista_datos2 =[]

def Automata_finito(texto):
    global lista_datos
    global lista_datos2
    estado = 1
    contador = 0
    almacemaniento = ""
    for i in range(0,len(texto)):
        cambio_estado = texto[i]
        if estado == 1:
          if cambio_estado.isdigit() :
            estado = 1
            contador = contador + 1
            almacemaniento = almacemaniento + cambio_estado
            lista_datos.append([almacemaniento,contador])

          elif cambio_estado == "-":
            estado = 2
            contador = contador + 1
            almacemaniento = almacemaniento + cambio_estado
            lista_datos.append([almacemaniento,contador])

          else:
            print("No es un numero ")
        
        elif estado == 2:
          if cambio_estado.isdigit():
            estado = 2
            contador = contador + 1
            almacemaniento = almacemaniento + cambio_estado
            lista_datos.append([almacemaniento,contador])
          elif cambio_estado =="-":
            estado = 3
            contador = contador + 1
            almacemaniento = almacemaniento + cambio_estado
            lista_datos.append([almacemaniento,contador])
          else:
            print("No es un numero ")
        elif estado == 3:
              
          if cambio_estado.isdigit():
            estado = 3
            contador = contador + 1
            almacemaniento = almacemaniento + cambio_estado
            lista_datos.append([almacemaniento,contador])

          else:
            
            print("No es un numero ")


        else:

          print("No es un numero ")
            
          
    if contador == len(texto):
      almacemaniento = almacemaniento + cambio_estado
      lista_datos2.append(almacemaniento)
                


    for j in lista_datos2:
      print("El numero telefonico es : ", j)
        

    
    



Automata_finito("555-888-87458")